version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5278:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "8725:1433"

        environment:
            SA_USERNAME: "sa"
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"